contatti/urls.py
from django.urls import path
from . import views

app_name = "contatti"

urlpatterns = [
    path("contattaci", views.contatti, name="contattaci"),
    path("lista", views.lista, name="lista"),
    path("eliminacontatto/<int:pk>", views.elimina_contatto, name="elimina-contatto"),
    path("modificacontatto/<int:pk>", views.modifica_contatto, name="modifica-contatto"),
]

news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.home, name="homeview"),
    path("articoli/<int:pk>", views.article_detail, name="articolodettaglio"),
    path("lista_articoli", views.list_articles, name="articolodettaglio"),
    path("lista_articoli/<int:pk>", views.list_articles, name="articolodettaglio"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root, chi_siamo

urlpatterns = [
    path("", index_root),
    path("chi_siamo", chi_siamo),
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
    path("news/", include("news.urls")),
    path("voti/", include("voti.urls")),
    path("corsi_formazione/", include("corsi_formazione.urls")),
    path("contatti/", include("contatti.urls"))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

primo_progetto_root/primo_progetto/primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root, chi_siamo

urlpatterns = [
    path("", index_root),
    path("chi_siamo", chi_siamo),
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
]

contatti/models.py
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    contents = models.TextField()

contatti/forms.py
from django import forms

from contatti.models import Contact


class ContattoForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    contents = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "testo"},))

    class Meta:
        model = Contact
        fields = "__all__"

contatti/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import Contact

from contatti.forms import ContattoForm

from django.shortcuts import get_object_or_404, redirect

from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.decorators import login_required


def index(request: HttpRequest) -> HttpResponse:
    form = ContattoForm()
    context = {"form": form}
    return render(request, "contatti_contattaci.html", context)


def contatti(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ContattoForm(request.POST)

        if form.is_valid():
            print("Form valido")
            print(f"Nome:\t\t{form.cleaned_data['first_name']}")
            print(f"Cognome:\t\t{form.cleaned_data['last_name']}")
            print(f"Email:\t\t{form.cleaned_data['email']}")
            print(f"Contenuti:\t\t{form.cleaned_data['contents']}")

            print("Salvataggio nel database")
            new_contact = form.save()
            print(f"New post: {new_contact}")

            return HttpResponse("<h1>risposta ricevuta</h1>")
    else:
        form = ContattoForm()

    context = {"form": form}
    return render(request, "contatti_contattaci.html", context)


def lista(request: HttpRequest) -> HttpResponse:
    context = {"contacts": Contact.objects.all()}
    return render(request, "contatti_lista.html", context)


@login_required(login_url="/accounts/login")
def modifica_contatto(request: HttpRequest, pk) -> HttpResponse:
    contatto = get_object_or_404(Contact, id=pk)

    if request.method == "GET":
        form = ContattoForm(instance=contatto)
    if request.method == "POST":
        form = ContattoForm(request.POST, instance=contatto)
        if form.is_valid():
            form.save()
            return redirect("contatti:lista")

    context = {"form": form, "contatto": contatto}
    return render(request, "modifica_contatto.html", context)


@staff_member_required(login_url="/accounts/login")
def elimina_contatto(request: HttpRequest, pk) -> HttpResponse:
    contatto = get_object_or_404(Contact, id=pk)
    if request.method == "POST":
        contatto.delete()
        return redirect("contatti:lista")
    context = {"contatto": contatto}

    return render(request, "elimina_contatot.html", context)

contatti/templates/contatti_contattaci.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{%block title%}
{{block.super}} | Contatti
{%endblock title%}

{%block content%}
<div class="container">
    <h1>Compila il form</h1>

    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-danger" value="invia">
    </form>
</div>
{%endblock content%}

contatti/templates/contatti_lista.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{%block title%}
{{block.super}} | Lista contatti
{%endblock title%}

{%block content%}
<div class="container">
    <h1>Lista dei contatti</h1>

    
    <p>
    <table class="table">
        <thead>
            <tr>
                {% if request.user.is_authenticated %}
                <th>Cancella</th>
                <th>Modifica</th>
                {% endif %}
                <th>Cognome</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Contenuti</th>
            </tr>
        </thead>
    {% for contact in contacts %}
        <tr>
            {% if request.user.is_authenticated %}
            <td><a href="{% url 'contatti:elimina-contatto' c.pk %}"><i class="fas fa-eraser"></i></a></td>
            <td><a href="{% url 'contatti:modifica-contatto' c.pk %}"><i class="far fa-edit"></i></a></td>
            {% endif %}
            <td>{{contact.last_name}}</td>
            <td>{{contact.first_name}}</td>
            <td>{{contact.email}}</td>
            <td>{{contact.contents}}</td>
        </tr>
    {% endfor %}
      </table>

    </p>
</div>
{%endblock content%}

contatti/templates/elimina_contatto.html
{% block content %}

<div class="container">
    <h1>Elimina contatto</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="CONFERMA ELIMINAZIONE">
    </form>
</div>

{% endblock content %}

contatti/templates/modifica_contatto.html
{%block content%}

<div class="container">
    <h1>Modifica contatto</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="SALVA MODIFICHE">
    </form>
</div>

{% endblock content %}