corsi_formazione/urls.py
from django.urls import path
from . import views

app_name = "corsi_formazione"

urlpatterns = [
    path("", views.index, name="index"),
    path("view_a", views.view_a, name="view_a"),
    path("view_b", views.view_b, name="view_b"),
    path("view_b_detail/<int:id>", views.view_b_detail, name="view_b_detail"),
    path("view_c", views.view_c, name="view_c"),
    path("view_d", views.view_d, name="view_d"),
    path("view_e", views.view_e, name="view_e"),
    path("view_f", views.view_f, name="view_f"),
]

news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.home, name="homeview"),
    path("articoli/<int:pk>", views.article_detail, name="articolodettaglio"),
    path("lista_articoli", views.list_articles, name="articolodettaglio"),
    path("lista_articoli/<int:pk>", views.list_articles, name="articolodettaglio"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root, chi_siamo

urlpatterns = [
    path("", index_root),
    path("chi_siamo", chi_siamo),
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
    path("news/", include("news.urls")),
    path("voti/", include("voti.urls")),
    path("corsi_formazione/", include("corsi_formazione.urls")),
    path("contatti/", include("contatti.urls"))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

primo_progetto_root/primo_progetto/primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root, chi_siamo

urlpatterns = [
    path("", index_root),
    path("chi_siamo", chi_siamo),
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
]

corsi_formazione/models.py
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    date_start = models.DateField()
    date_end = models.DateField()
    available_seats = models.PositiveIntegerField()

    def __str__(self) -> str:
        return f"Corso: {self.title}, dal {self.date_start} al {self.date_end}, {self.available_seats} posti"

corsi_formazione/views.py
from datetime import date

from django.db.models import Max, Min, Sum
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, render

from corsi_formazione.models import Course


def index(request: HttpRequest):
    return render(request, "corsi_base.html")


def view_a(request: HttpRequest):
    courses = Course.objects.all().order_by("date_start")
    context = {"courses": courses}
    return render(request, "view_a.html", context=context)


def view_b(request: HttpRequest):
    courses = Course.objects.all().order_by("date_start")
    context = {"courses": courses}
    return render(request, "view_b.html", context=context)


def view_b_detail(request: HttpRequest, id: int):
    course = get_object_or_404(Course, pk=id)
    context = {"course": course}
    return render(request, "view_b_detail.html", context=context)


def view_c(request: HttpRequest):
    courses = Course.objects.filter(date_start__gt=date(year=2025, month=5, day=1))
    context = {"courses": courses}
    return render(request, "view_c.html", context=context)


def view_d(request: HttpRequest):
    courses = Course.objects.filter(available_seats__lt=20)
    context = {"courses": courses}
    return render(request, "view_d.html", context=context)


def view_e(request: HttpRequest):
    courses = Course.objects.filter(date_end__lt=date(year=2025, month=4, day=30))
    context = {"courses": courses}
    return render(request, "view_e.html", context=context)


def view_f(request: HttpRequest):
    seats_data = Course.objects.all().aggregate(
        total_seats=Sum("available_seats"),
        most_seats=Max("available_seats"),
        least_seats=Min("available_seats"),
    )

    most_seats = (
        Course.objects.filter(available_seats=seats_data["most_seats"]).first()
        or "Nessun corso trovato!"
    )
    least_seats = (
        Course.objects.filter(available_seats=seats_data["least_seats"]).first()
        or "Nessun corso trovato!"
    )

    context = {
        "most_seats": most_seats,
        "least_seats": least_seats,
        "total_seats": seats_data["total_seats"],
    }

    return render(request, "view_f.html", context=context)

corsi_formazione/templates/corsi_base.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Corsi formazione{% endblock title %}</title>
</head>
<body>
    {% block content %}
    <h1>Benvenuto nel sistema di gestione dei Corsi di Formazione</h1>
    <ul>
      <li><a href="{% url 'corsi_formazione:view_a' %}">Lista dei Corsi</a></li>
      <li><a href="{% url 'corsi_formazione:view_b' %}">Dettagli dei Corsi</a></li>
      <li><a href="{% url 'corsi_formazione:view_c' %}">Corsi che iniziano dopo il 01/05/2025</a></li>
      <li><a href="{% url 'corsi_formazione:view_d' %}">Corsi con meno di 20 posti disponibili</a></li>
      <li><a href="{% url 'corsi_formazione:view_e' %}">Corsi che terminano entro il 30/04/2025</a></li>
      <li><a href="{% url 'corsi_formazione:view_f' %}">Statistiche Avanzate sui Corsi</a></li>
    </ul>
    <hr>
    {% endblock content %}
</body>
</html>

corsi_formazione/templates/view_a.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Lista corsi{% endblock title %}

{% block content %}
{{block.super}}

<ul>
{% for course in courses %}
    <li>{{course}}</li>
{% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/view_b.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Dettaglio corso {% endblock title %}

{% block content %}
{{block.super}}

<ul>
{% for course in courses %}
<li> <a href="view_b_detail/{{course.id}}">{{course}}</a></li>
{% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/view_b_detail.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Dettaglio corso {% endblock title %}

{% block content %}
{{block.super}}

<h2>{{course.title}}</h2>

<p>{{course.description}}</p>

<p>Dal {{course.date_start}} al {{course.date_end}}</p>
<p><i>Posti disponibili: {{course.available_seats}}</i></p>

{% endblock content %}

corsi_formazione/templates/view_c.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Dopo 1 Maggio {% endblock title %}

{% block content %}
{{block.super}}

<ul>
{% for course in courses %}
<li> <a href="view_b_detail/{{course.id}}">{{course}}</a></li>
{% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/view_d.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Meno di 20 posti {% endblock title %}

{% block content %}
{{block.super}}

<ul>
{% for course in courses %}
<li> <a href="view_b_detail/{{course.id}}">{{course}}</a></li>
{% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/view_e.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Entro 30 Aprile {% endblock title %}

{% block content %}
{{block.super}}

<ul>
{% for course in courses %}
<li> <a href="view_b_detail/{{course.id}}">{{course}}</a></li>
{% endfor %}
</ul>

{% endblock content %}

corsi_formazione/templates/view_f.html
{% extends "corsi_base.html" %}

{% block title %}{{block.super}} | Dati {% endblock title %}

{% block content %}
{{block.super}}

<ul>
    <li>Corso con più posti disponibili: {{most_seats.title}} ({{most_seats.available_seats}} posti)</li>
    <li>Corso con meno posti disponibili: {{least_seats.title}} ({{least_seats.available_seats}} posti)</li>
    <li>Posti totali: {{total_seats}}</li>
</ul>

{% endblock content %}