contatti/urls.py
from django.urls import path
from . import views

app_name = "contatti"

urlpatterns = [
    path("contattaci", views.contatti, name="contattaci"),
    path("lista", views.lista, name="lista"),
    path("eliminacontatto/<int:pk>", views.elimina_contatto, name="elimina-contatto"),
    path("modificacontatto/<int:pk>", views.modifica_contatto, name="modifica-contatto"),
]

news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path("", views.home, name="homeview"),
    path("articoli/<int:pk>", views.article_detail, name="articolodettaglio"),
    path("lista_articoli", views.list_articles, name="articolodettaglio"),
    path("lista_articoli/<int:pk>", views.list_articles, name="articolodettaglio"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, lista, welcome, variabili, index

app_name = "prima_app"

urlpatterns = [
    path("", index, name="index"),
    path("homepage", homepage, name="homepage"),
    path("welcome", welcome, name="welcome"),
    path("lista", lista, name="lista"),
    path("variabili", variabili, name="variabili")
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root, chi_siamo

urlpatterns = [
    path("", index_root),
    path("chi_siamo", chi_siamo),
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
    path("news/", include("news.urls")),
    path("voti/", include("voti.urls")),
    path("corsi_formazione/", include("corsi_formazione.urls")),
    path("contatti/", include("contatti.urls"))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

primo_progetto_root/primo_progetto/primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root, chi_siamo

urlpatterns = [
    path("", index_root),
    path("chi_siamo", chi_siamo),
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
]

seconda_app/urls.py
from django.urls import path 
from seconda_app.views import es_if, es_for

app_name = "seconda_app"

urlpatterns = [
    path("es_if", es_if, name="es_if"),
    path("es_for", es_for, name="es_for")
]

voti/urls.py
from django.urls import path
from . import views

app_name = "voti"

urlpatterns = [
    path("", views.subjects_list, name="vista_1"),
    path("vista_2", views.student_grades, name="vista_2"),
    path("vista_3", views.student_averages, name="vista_3"),
    path("vista_4", views.max_and_min_grades, name="vista_4"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

        <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
              <a class="navbar-brand" href="/">Primo progetto</a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prima app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'prima_app:homepage' %}">Homepage</a>
            <a class="dropdown-item" href="{% url 'prima_app:welcome' %}">Benvenuto</a>
            <a class="dropdown-item" href="{% url 'prima_app:lista' %}">Lista</a>
            <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Seconda app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'seconda_app:es_if' %}">Es if</a>
            <a class="dropdown-item" href="{% url 'seconda_app:es_for' %}">Es for</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Voti
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'voti:vista_1' %}">Materie</a>
            <a class="dropdown-item" href="{% url 'voti:vista_2' %}">Studenti</a>
            <a class="dropdown-item" href="{% url 'voti:vista_3' %}">Medie</a>
            <a class="dropdown-item" href="{% url 'voti:vista_4' %}">Voto massimo / minimo</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          News
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'news:homeview' %}">Articoli</a>
            <a class="dropdown-item" href="{% url 'news:articolodettaglio' %}">Articoli (dettaglio)</a>
        </div>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Contatti
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'contatti:contattaci' %}">Contattaci</a>
            <a class="dropdown-item" href="{% url 'contatti:lista' %}">Lista contatti</a>
        </div>
      </li>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Corsi formazione
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'corsi_formazione:view_a' %}">View a</a>
            <a class="dropdown-item" href="{% url 'corsi_formazione:view_b' %}">View b</a>
            <a class="dropdown-item" href="{% url 'corsi_formazione:view_c' %}">View c</a>
            <a class="dropdown-item" href="{% url 'corsi_formazione:view_d' %}">View d</a>
            <a class="dropdown-item" href="{% url 'corsi_formazione:view_e' %}">View e</a>
            <a class="dropdown-item" href="{% url 'corsi_formazione:view_f' %}">View f</a>
        </div>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown">
          {{ request.user.username }}
        </a>
        <div class="dropdown-menu">
          <div class="dropdown-divider"></div>
          <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{% url 'contatti:contattaci' %}" class="nav-link">Registrati</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'login' %}" class="nav-link">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
        </nav>
        <div class="container my-4">
            {% block content %}
            {% endblock content %}

            {% block script %}
            {% endblock script %}
        </div>
  </body>
</html>

templates/chi_siamo.html
{% extends "base.html" %}

{% block title %} {{block.super}} | Chi siamo {% endblock title %}

{% block content %}
    <h1>Chi siamo</h1>
    <p>...</p>
{% endblock content %}

templates/index_root.html
{% extends 'base.html' %}

{% block title %}
Index
{%endblock title %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index root</title>
</head>
<body>
   <h1>Index root</h1> 
    <ol>
        <li><a href="/admin">Admin panel</a></li>
        <li><a href="{% url 'prima_app:index' %}">Index prima app</a></li>
    </ol>
</body>
</html> {% endcomment %}